services:
  product_api:
    build: ./products
    command: python -m uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./products:/code
    ports:
      - "3341:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AI_FOR_THAI_KEY=${AI_FOR_THAI_KEY}
  user_api:
    build: ./users
    command: python -m uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./users:/code
    ports:
      - "3342:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AI_FOR_THAI_KEY=${AI_FOR_THAI_KEY}
